language: node_js
os: linux
node_js:
   - "10"

before_script:
   - npm install
   - npm install --save-dev mocha chai

jobs:
   include:
   - stage: test
     script: echo test
     if: branch =~ /^feature\/.*$/
   
   - stage: deploy
     script: echo deploy
     if: branch =~ /master/

