language: node_js
os: linux
node_js:
   - "10"

jobs:
   include:
      - stage: "test"
        name: "Run unit test"
        before_script:
           - npm install
           - npm install --save-dev mocha chai
        script: npm test
        if: branch = master

      - stage: "build"
        name: "Push to docker hub"
        services: 
          - docker
        script:
           - dockerpass=`echo $DOCKER_PASSWORD | base64 -d`
           - dockeruser=`echo $DOCKER_USERNAME | base64 -d`
           - echo "$dockerpass" | docker login -u "$dockeruser" --password-stdin
           - docker build -t luanngominh/frontend-ci .
           - docker push luanngominh/frontend-ci
        #if: branch = master

      - stage: "deploy"
        name: "Deploy app to kube"
        script: echo meowmeow
        if: branch = master

notifications:
   email:
      recipients:
      - luannm@dwarvesv.com
      on_success: always
      on_failure: always
