language: node_js
os: linux
node_js:
   - "10"

before_script:
   - npm install
   - npm install --save-dev mocha chai

script:
   - npm test

notifications:
   email:
      recipients:
      - luannm@dwarvesv.com
      on_success: always
      on_failure: always
