language: node_js
os: linux
node_js:
   - "10"

before_script:
   - npm install
   - npm install --save-dev mocha chai

jobs:
   include:
      - stage: "test"
        name: "Run unit test"
        script: npm test

      - stage: "deploy"
        name: "Deploy to heroku"
        script: echo deploy
        if: branch =~ /master/

notifications:
   email:
      recipients:
      - luannm@dwarvesv.com
      on_success: always
      on_failure: always
