language: node_js
os: linux
node_js:
   - "10"

jobs:
   include:
      - stage: "test"
        name: "Run unit test"
        before_script:
           - npm install
           - npm install --save-dev mocha chai
        script: npm test; echo $docker_password

      - stage: "build"
        name: "Push to docker hub"
        services: 
          - docker
        script:
           - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
           - docker build -t frontend-ci .
           - docker push frontend-ci
        #if: branch = master

      - stage: "deploy"
        name: "Deploy app to kube"
        script: echo meowmeow
        if: branch = master

notifications:
   email:
      recipients:
      - luannm@dwarvesv.com
      on_success: always
      on_failure: always
